default_platform(:android)

platform :android do
  desc "Distribute dev flavor to Firebase"
  lane :dev do
    build_flutter_app(flavor: "dev")
    upload_to_firebase(flavor: "dev")
  end

  desc "Distribute staging flavor to Firebase"
  lane :staging do
    build_flutter_app(flavor: "staging")
    upload_to_firebase(flavor: "staging")
  end

  desc "Distribute prod flavor to Firebase"
  lane :prod do
    build_flutter_app(flavor: "prod")
    upload_to_firebase(flavor: "prod")
  end

  private_lane :build_flutter_app do |options|
    flavor = options[:flavor]
    sh("flutter build apk --flavor #{flavor} -t lib/main_#{flavor}.dart")
  end

  private_lane :upload_to_firebase do |options|
    flavor = options[:flavor]
    firebase_app_id = case flavor
      when "dev" then "1:802005387528:android:bf6844f1b7b467ec0d84bd"
      when "staging" then "1:802005387528:android:1ff262f52df7668d0d84bd"
      when "prod" then "1:802005387528:android:0b46b197c8d1b92d0d84bd"
    end

    apk_path = File.expand_path("../../../build/app/outputs/flutter-apk/app-#{flavor}-release.apk", __FILE__)
    service_credentials_file = File.expand_path("../../../firebase_service_account.json", __FILE__)

    firebase_app_distribution(
      app: firebase_app_id,
      apk_path: apk_path,
      release_notes: "New build for #{flavor} flavor",
      testers: "dev.thantzin@gmail.com",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      service_credentials_file: service_credentials_file

    )
  end
end
